//========================================================================================
//  
//  $File: $
//  
//  Owner: Ross Edgar
//  
//  $Author: $
//  
//  $DateTime: $
//  
//  $Revision: $
//  
//  $Change: $
//  
//  Copyright 1997-2008 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================
//REGISTER_PMINTERFACE(TypesetContinuedLinesActionComponent, kTypesetContinuedLinesActionComponentImpl)
// YOU'RE GONNA HAVE TO MAKE THIS WORK:
REGISTER_PMINTERFACE(CL_TypesetContinuedLinesWorkhorse, kTypesetContinuedLinesImpl)

//  Code generated by DollyXs code generator
